# Site settings
title: Sameer S Sahasrabudhe
email: sameesss@iitgn.ac.in
description: Personal webpage of Dr. Sameer S Sahasrabudhe
baseurl: ""
url: ""

# Google analytics ID: Uncomment and your own, if you like
# google_analytics: XX
# google_analytics_4: XXX
# google_tag_manager: XXX

# Footer info
affiliation: >
  Indian Institute of Technology Gandhinagar<br/>
  Dr. Sameer S Sahasrabudhe<br/>
  IITGN

location: >  
  Indian Institute of Technology Gandhinagar<br/>
  Palaj, Gandhinagar, Gujarat 382355<br/>
  India

contact: >
  <a href="mailto:sameesss@iitgn.ac.in" target="_blank" style="color:CornflowerBlue"><i class="fa fa-envelope fa-1x" style="color:CornflowerBlue"></i> Contact Sameer S Sahasrabudhe via email</a> <br/>
  <a href="https://github.com/sameesss" style="color:CornflowerBlue"><i class="fa fa-github fa-1x" style="color:CornflowerBlue"></i> My GitHub Profile</a>

# Pages shown in navbar
nav_pages:    
  - name: about
  - name: talks
  - name: research
  - name: publications  
  - name: teaching
  - name: blogs
  - name: films


include:
  - .htaccess
  - _pages

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true # default for kramdown is false. This will enable using Markdown links

plugins: ["jekyll/scholar"]

scholar:
  last_name: Sahasrabudhe
  first_name: [Sameer, S]

  style: citesty
  locale: en

  source: /assets/
  bibliography: sahasrabudhe_publications.bib
  bibliography_template: bibtemplate
  sort_by: year, month
  order: descending

  replace_strings: true
  join_strings: true

  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details

  query: "@*"

  bibliography_list_attributes:
    reversed: "reversed"

exclude:
  - Gemfile
  - Gemfile.lock
  - update_boostrap.sh
  - switch_theme.sh
  - tags
  - Rakefile
